const ESPECE = [
  {
    id_espece: "1",
    nom: "Tigre",
    genre: "Panthera",
    famille: "Falidae",
    ordre: "Carnivora",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "2",
    nom: "Lion",
    genre: "Panthera",
    famille: "Falidae",
    ordre: "Carnivora",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "3",
    nom: "Couleuvre de Montpellier",
    genre: "Malpolon",
    famille: "Lamprophiidae",
    ordre: "Squamata",
    classe: "Reptilia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "4",
    nom: "Koala",
    genre: "Phascolarctos",
    famille: "Phascolarctidae",
    ordre: "Diprotodontia",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "5",
    nom: "Aigle Royal",
    genre: "Aquila",
    famille: "Accipitridae",
    ordre: "Accipitriformes",
    classe: "Aves",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "6",
    nom: "Loup gris commun",
    genre: "Canis",
    famille: "Canidae",
    ordre: "Carnivora",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "7",
    nom: "Moineau domestique",
    genre: "Passer",
    famille: "Passeridae",
    ordre: "Passeriformes",
    classe: "Aves",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "8",
    nom: "Anguille d'Europe",
    genre: "Anguilla",
    famille: "Anguillidae",
    ordre: "Anguilliformes",
    classe: "Actinopterygii",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "9",
    nom: "Baleine bleue",
    genre: "Balaenoptera",
    famille: "Balaenopteridae",
    ordre: "Celacea",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "10",
    nom: "Sapin blanc",
    genre: "Abies",
    famille: "Pinaceae",
    ordre: "Pinales",
    classe: "Pinopsida",
    embranchement: "N/A",
    regne: "Plantae",
  },
  {
    id_espece: "11",
    nom: "Cyprès du Maroc",
    genre: "Cupressus",
    famille: "Cupressaceae",
    ordre: "Pinales",
    classe: "Pinopsida",
    embranchement: "N/A",
    regne: "Plantae",
  },
  {
    id_espece: "12",
    nom: "Bouquetin des Alpes",
    genre: "Capra",
    famille: "Bovidae",
    ordre: "Artiodactyla",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "13",
    nom: "Bos tauras",
    genre: "Bos",
    famille: "Bovidae",
    ordre: "Artiodactyla",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "14",
    nom: "Perruche à collier",
    genre: "Psittacula",
    famille: "Psittacidae",
    ordre: "Psittaciformes",
    classe: "Aves",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "15",
    nom: "Edelweiss",
    genre: "Leontopodium",
    famille: "Asteraceae",
    ordre: "Asterales",
    classe: "Magnoliopsida",
    embranchement: "N/A",
    regne: "Plantae",
  },
  {
    id_espece: "16",
    nom: "Couteau commun",
    genre: "Ensis",
    famille: "Pharidae",
    ordre: "Veneroida",
    classe: "Bivalvia",
    embranchement: "Mollusca",
    regne: "Animalia",
  },
  {
    id_espece: "17",
    nom: "Abeille européenne",
    genre: "Apis",
    famille: "Apidae",
    ordre: "Hymenoptera",
    classe: "Insecta",
    embranchement: "Arthropoda",
    regne: "Animalia",
  },
  {
    id_espece: "18",
    nom: "Chevreuil",
    genre: "Capreolus",
    famille: "Cervidae",
    ordre: "Artiodactyla",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "19",
    nom: "Rouge-gorge familier",
    genre: "Erithacus",
    famille: "Muscicapidae",
    ordre: "Passeriformes",
    classe: "Aves",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "20",
    nom: "Blaireau européen",
    genre: "Meles",
    famille: "Mustelidae",
    ordre: "Carnivora",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "21",
    nom: "Castor fiber",
    genre: "Castor",
    famille: "Castoridae",
    ordre: "Rodentia",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "22",
    nom: "Ours brun",
    genre: "Ursus",
    famille: "Ursidae",
    ordre: "Carnivora",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "23",
    nom: "Seiche commune",
    genre: "Sepia",
    famille: "Sepiidae",
    ordre: "Sepiida",
    classe: "Cephalopoda",
    embranchement: "Mollusca",
    regne: "Animalia",
  },
  {
    id_espece: "24",
    nom: "Taupe d'Europe",
    genre: "Talpa",
    famille: "Talpidae",
    ordre: "Soricomorpha",
    classe: "Mammalia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
  {
    id_espece: "25",
    nom: "Processionnaire du pin",
    genre: "Thaumetopoea",
    famille: "Notodontidae",
    ordre: "Lepidoptera",
    classe: "Insecta",
    embranchement: "Arthropoda",
    regne: "Animalia",
  },
  {
    id_espece: "26",
    nom: "Python d'Angola",
    genre: "Python",
    famille: "Pythonidae",
    ordre: "Squamata",
    classe: "Reptilia",
    embranchement: "Chordata",
    regne: "Animalia",
  },
];

export default ESPECE;
