const PERSONNEL = [
  {
    id_personnel: "1",
    nom: "Dupont",
    prenom: "Michel",
    poste: "Salarie",
    email: null,
    id_site: "1",
  },
  {
    id_personnel: "2",
    nom: "Table",
    prenom: "Julien",
    poste: "Benevole",
    email: null,
    id_site: "2",
  },
  {
    id_personnel: "3",
    nom: "Jeanne",
    prenom: "Marie",
    poste: "Benevole",
    email: null,
    id_site: "3",
  },
  {
    id_personnel: "4",
    nom: "De la Phantecte",
    prenom: "Jean-Mouloud",
    poste: "PDG",
    email: "jeanmouloud.delaphantecte@archedenoe.com",
    id_site: null,
  },
  {
    id_personnel: "6",
    nom: "Fenêtre",
    prenom: "Montequilla",
    poste: "Benevole",
    email: null,
    id_site: "3",
  },
  {
    id_personnel: "7",
    nom: "Chemin",
    prenom: "Jean",
    poste: "Benevole",
    email: null,
    id_site: "3",
  },
  {
    id_personnel: "8",
    nom: "De terre",
    prenom: "Albert",
    poste: "Benevole",
    email: null,
    id_site: "2",
  },
  {
    id_personnel: "9",
    nom: "But",
    prenom: "Mark",
    poste: "Benevole",
    email: null,
    id_site: "2",
  },
  {
    id_personnel: "10",
    nom: "Padidé",
    prenom: "Gené",
    poste: "Benevole",
    email: null,
    id_site: "2",
  },
  {
    id_personnel: "11",
    nom: "Frère",
    prenom: "Jaques",
    poste: "Benevole",
    email: null,
    id_site: "2",
  },
  {
    id_personnel: "12",
    nom: "Lait",
    prenom: "Gary",
    poste: "Benevole",
    email: null,
    id_site: "1",
  },
  {
    id_personnel: "13",
    nom: "Croche",
    prenom: "Sarah",
    poste: "Benevole",
    email: null,
    id_site: "1",
  },
  {
    id_personnel: "14",
    nom: "Refrain",
    prenom: "Dominique",
    poste: "Benevole",
    email: null,
    id_site: "1",
  },
  {
    id_personnel: "15",
    nom: "Lent",
    prenom: "Axel",
    poste: "Benevole",
    email: null,
    id_site: "1",
  },
  {
    id_personnel: "16",
    nom: "Ho Lee Fuc",
    prenom: "Tao",
    poste: "Benevole",
    email: null,
    id_site: "3",
  },
  {
    id_personnel: "17",
    nom: "Livre",
    prenom: "Martine",
    poste: "Benevole",
    email: null,
    id_site: "2",
  },
  {
    id_personnel: "18",
    nom: "Caillou",
    prenom: "Camille",
    poste: "Benevole",
    email: null,
    id_site: "2",
  },
];

export default PERSONNEL;
