const UTILISATEUR = [
  {
    id_utilisateur: "1",
    login: "Dupont",
    password: "Michel",
    admin: "1",
    id_personnel: "1",
  },
  {
    id_utilisateur: "2",
    login: "Table",
    password: "Julien",
    admin: "0",
    id_personnel: "2",
  },
  {
    id_utilisateur: "3",
    login: "Jeanne",
    password: "Marie",
    admin: "0",
    id_personnel: "3",
  },
  {
    id_utilisateur: "4",
    id_personnel: "6",
    login: "Fenêtre",
    password: "Montequilla",
    admin: null,
  },
  {
    id_utilisateur: "5",
    id_personnel: "7",
    login: "Chemin",
    password: "Jean",
    admin: null,
  },
  {
    id_utilisateur: "6",
    id_personnel: "8",
    login: "De terre",
    password: "Albert",
    admin: null,
  },
  {
    id_utilisateur: "7",
    id_personnel: "9",
    login: "But",
    password: "Mark",
    admin: null,
  },
  {
    id_utilisateur: "8",
    id_personnel: "10",
    login: "Padidé",
    password: "Gené",
    admin: null,
  },
  {
    id_utilisateur: "9",
    id_personnel: "11",
    login: "Frère",
    password: "Jaques",
    admin: null,
  },
  {
    id_utilisateur: "10",
    id_personnel: "12",
    login: "Lait",
    password: "Gary",
    admin: null,
  },
  {
    id_utilisateur: "11",
    id_personnel: "13",
    login: "Croche",
    password: "Sarah",
    admin: null,
  },
  {
    id_utilisateur: "12",
    id_personnel: "14",
    login: "Refrain",
    password: "Dominique",
    admin: null,
  },
  {
    id_utilisateur: "13",
    id_personnel: "15",
    login: "Lent",
    password: "Axel",
    admin: null,
  },
  {
    id_utilisateur: "14",
    id_personnel: "16",
    login: "Ho Lee Fuc",
    password: "Tao",
    admin: null,
  },
  {
    id_utilisateur: "15",
    id_personnel: "17",
    login: "Livre",
    password: "Martine",
    admin: null,
  },
  {
    id_utilisateur: "16",
    id_personnel: "18",
    login: "Caillou",
    password: "Camille",
    admin: null,
  },
];

export default UTILISATEUR;
